linters:
  enable:
    - revive
  disable:
    - deadcode
    - unused
    - structcheck
    - varcheck

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  errcheck:
    exclude: scripts/errcheck_excludes.txt
