{
 "title": "messages",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(up{from=\"emqx\",cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_messages_sent{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_messages_received{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages Dropped Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_messages_dropped{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}