{
 "title": "Client Events",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values({from='emqx',cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_client_connected{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} Connection"
    }
   ]
  },
  {
   "title": "Disconnection Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_client_disconnected{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} Disconnection"
    }
   ]
  },
  {
   "title": "Sub Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_client_subscribe{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} Subscribe"
    }
   ]
  },
  {
   "title": "Unsub Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_client_unsubscribe{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} Unsubscribe"
    }
   ]
  },
  {
   "title": "Connect Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_client_authenticate{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} Connection Auth"
    }
   ]
  },
  {
   "title": "ACL Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_client_check_acl{cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} ACL Auth"
    }
   ]
  },
  {
   "title": "Anonymous Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_client_auth_success_anonymous {cluster=\"$cluster\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} Anonymous Auth"
    }
   ]
  }
 ]
}