{
 "title": "Rule Engine",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   { "name": "node", "query": { "query": "label_values(node)" } },
   { "name": "rule", "query": { "query": "label_values(rule)" } }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rule Engine Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(node, rule) (emqx_rule_exec_rate{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "{{ node }} {{ rule }}"
    }
   ]
  },
  {
   "title": "Rule Engine Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(node, rule) (emqx_rule_exec_last5m_rate{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "{{ node }}:{{ rule }}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Rule Engine Execute Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(node, rule) (emqx_rule_topic_hit_count{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "Topic Hit Cout"
    },
    {
     "expr": "max by(node, rule) (emqx_rule_exec_max_rate{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "Max Rate"
    },
    {
     "expr": "sum by(node, rule) (emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "Exec Pass"
    },
    {
     "expr": "sum by(node, rule) (increase(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"}[15m]))",
     "legendFormat": "Exec Failure"
    },
    {
     "expr": "sum by(node, rule) (emqx_rule_exec_no_result_count{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "Exec No Result"
    },
    {
     "expr": "sum by(node, rule) (emqx_rule_action_total{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "Action Total"
    },
    {
     "expr": "sum by(node, rule) (emqx_rule_action_success{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"})",
     "legendFormat": "Action Success"
    },
    {
     "expr": "sum by(node, rule) (increase(emqx_rule_action_failed{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"}[15m]))",
     "legendFormat": "Action Failed"
    }
   ]
  },
  { "title": "$rule Failure Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "rule" },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "node",
   "targets": [
    {
     "expr": "sum by(node, rule) (increase(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"}[$__interval]))",
     "legendFormat": "{{node}} {{ rule }} Exec Failure"
    },
    {
     "expr": "sum by(node, rule) (increase(emqx_rule_action_failed{cluster=\"$cluster\", node=~\"$node\", rule=~\"$rule\"}[$__interval]))",
     "legendFormat": "{{node}} {{ rule }} Action Failure"
    }
   ]
  }
 ]
}