{
 "title": "EMQX",
 "description": "Default EMQX Grafana Monitoring Dashboard Template",
 "tags": [
  "EMQX",
  "MQTT"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emqx_cluster_status{cluster=\"$cluster\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Nodes Running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max(emqx_cluster_nodes_running{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max(emqx_cluster_nodes_stopped{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Stopped"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  {
   "title": "Rule Engine Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_live_connections_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(instance) (emqx_connections_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ACL Auth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(emqx_packets_publish_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Publish ACL Failure"
    },
    {
     "expr": "sum(increase(emqx_packets_subscribe_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Sub ACL Failure "
    }
   ]
  },
  {
   "title": "Cluster Traffic Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(emqx_bytes_received{instance=~\".*\",cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(increase(emqx_bytes_sent{instance=~\".*\",cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Messages Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(emqx_messages_received{instance=~\".*\",cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Messages Received"
    },
    {
     "expr": "sum(increase(emqx_messages_sent{instance=~\".*\",cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Messages Sent"
    },
    {
     "expr": "sum(increase(emqx_messages_dropped{instance=~\".*\",cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(emqx_sessions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Connect Auth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__interval])) - sum(increase(emqx_packets_connack_error {instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Auth Success"
    },
    {
     "expr": "sum(increase(emqx_packets_connack_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Auth Failure"
    }
   ]
  },
  {
   "title": "Messages QOS Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(emqx_messages_qos0_received{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "QOS0"
    },
    {
     "expr": "sum(increase(emqx_messages_qos1_received{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "QOS1"
    },
    {
     "expr": "sum(increase(emqx_messages_qos2_received{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "QOS2"
    }
   ]
  },
  {
   "title": "Rule Engine Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_exec_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  },
  { "title": "Event", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Client Connection Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(emqx_client_connected{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(increase(emqx_client_disconnected{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Disconnections"
    }
   ]
  },
  {
   "title": "Client Connect Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(emqx_client_authenticate{cluster=\"$cluster\",instance=~\".*\"}[$__interval]))",
     "legendFormat": "Connect Auth"
    },
    {
     "expr": "sum(increase(emqx_client_auth_success_anonymous{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "Anonymous Auth"
    }
   ]
  },
  {
   "title": "Client ACL Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(emqx_client_check_acl{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "ACL Auth"
    }
   ]
  },
  {
   "title": "Client Sub Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(emqx_client_subscribe{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "Subscribes"
    },
    {
     "expr": "sum(increase(emqx_client_unsubscribe{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "Unsubscribes"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Packets Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Connect"
    },
    {
     "expr": "sum(increase(emqx_packets_connack_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Connack Sent"
    },
    {
     "expr": "sum(increase(emqx_packets_connack_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Connack Error"
    }
   ]
  },
  {
   "title": "Packets Disconnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(emqx_packets_disconnect_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Disconnect Sent"
    },
    {
     "expr": "sum(increase(emqx_packets_disconnect_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Disconnect Received"
    }
   ]
  },
  {
   "title": "Packets Publish",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(emqx_packets_publish_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Sent"
    },
    {
     "expr": "sum(increase(emqx_packets_publish_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Received"
    },
    {
     "expr": "sum(increase(emqx_packets_publish_dropped{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Dropped"
    },
    {
     "expr": "sum(increase(emqx_packets_publish_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Error"
    }
   ]
  },
  {
   "title": "Packets Subscribe/Unsubscribe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(emqx_packets_subscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Subscribe Received"
    },
    {
     "expr": "sum(increase(emqx_packets_suback_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Suback Sent"
    },
    {
     "expr": "sum(increase(emqx_packets_subscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Subscribe Error"
    },
    {
     "expr": "sum(increase(emqx_packets_unsubscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Unsubscribe Received"
    },
    {
     "expr": "sum(increase(emqx_packets_unsubscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Unsubscribe Error"
    }
   ]
  },
  { "title": "Rule Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Data Bridge Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(type, name) (emqx_rule_bridge_status{cluster=\"$cluster\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Rule Engine Execute Count",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 40 },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_topic_hit_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Topic Hit Cout"
    },
    {
     "expr": "max by(rule) (emqx_rule_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Max Rate"
    },
    {
     "expr": "sum by(rule) (emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Exec Pass"
    },
    {
     "expr": "sum by(rule) (increase(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\".*\"}[15m]))",
     "legendFormat": "Exec Failure"
    },
    {
     "expr": "sum by(rule) (emqx_rule_exec_no_result_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Exec No Result"
    },
    {
     "expr": "sum by(rule) (emqx_rule_action_total{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Action Total"
    },
    {
     "expr": "sum by(rule) (emqx_rule_action_success{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Action Success"
    },
    {
     "expr": "sum by(rule) (increase(emqx_rule_action_failed{cluster=\"$cluster\", node=~\".*\"}[15m]))",
     "legendFormat": "Action Failed"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Erlang VM Run Queue",
   "type": "timeseries",
   "description": "The value of run_queue_length can be used to evaluate the current Erlang scheduler load. If the value of run_queue_length is high, it means that there are many processes waiting to be executed in the run queue, and the scheduler may need more processor cores or a better scheduling strategy to better handle these processes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by(instance) (erlang_vm_statistics_run_queues_length_total{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }} Run Queue Length"
    }
   ]
  },
  {
   "title": "Erlang VM Process",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "max by(instance) (erlang_vm_process_limit{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }} Max Process limit"
    },
    {
     "expr": "sum by(instance) (erlang_vm_process_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }} Process Count"
    }
   ]
  },
  {
   "title": "Erlang VM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (emqx_vm_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}