{
 "title": "Authorization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values({cluster=\"$cluster\", from=\"exporter\"}, node)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(emqx_authorization_resource_status{cluster=\"$cluster\"},resource)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Authorize Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(node, resource) (emqx_authorization_exec_max_rate{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "Max Rate"
    },
    {
     "expr": "sum by(node, resource) (emqx_authorization_total{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(node, resource) (emqx_authorization_allow_count{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "Allow"
    },
    {
     "expr": "sum by(node, resource) (irate(emqx_authorization_deny_count{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"}[15m]))",
     "legendFormat": "Deny"
    }
   ]
  },
  {
   "title": "Authorize Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(node, resource) (emqx_authorization_exec_rate{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "{{node}} {{resource}}"
    }
   ]
  },
  {
   "title": "Authorize Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by(node, resource) (emqx_authorization_exec_last5m_rate{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "{{node}} {{resource}}"
    }
   ]
  }
 ]
}