{
 "title": "EMQX",
 "description": "Default EMQX Grafana Monitoring Dashboard Template",
 "tags": [
  "EMQX",
  "MQTT"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\".*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(emqx_topics_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Active Topics"
    }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "max(emqx_cluster_nodes_running{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max(emqx_cluster_nodes_stopped{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Stopped"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(instance) (emqx_connections_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "max(emqx_topics_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Topics"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  { "title": "Event", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Client Connection Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(irate(emqx_client_connected{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Total Connections"
    },
    {
     "expr": "sum(irate(emqx_client_disconnected{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Total Disconnections"
    },
    {
     "expr": "sum by(instance) (irate(emqx_client_connected{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ instance }} Connection"
    },
    {
     "expr": "sum by(instance) (irate(emqx_client_disconnected{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ instance }} Disconnection"
    }
   ]
  },
  {
   "title": "Client Pub/Sub Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(irate(emqx_client_subscribe{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "Total Subscribes"
    },
    {
     "expr": "sum(irate(emqx_client_unsubscribe{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "Total Unsubscribes"
    },
    {
     "expr": "sum by(instance) (irate(emqx_client_subscribe{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ instance }} Subscribe"
    },
    {
     "expr": "sum by(instance) (irate(emqx_client_unsubscribe{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ instance }} Unsubscribe"
    }
   ]
  },
  {
   "title": "Client Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(irate(emqx_client_authenticate{cluster=\"$cluster\",instance=~\".*\"}[$__interval]))",
     "legendFormat": "Total Client Authentications"
    },
    {
     "expr": "sum(irate(emqx_client_auth_anonymous{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "Total Anonymous Auth Clients"
    },
    {
     "expr": "sum(irate(emqx_client_authorize{cluster=\"$cluster\", instance=~\".*\"}[$__interval]))",
     "legendFormat": "Total Client Authorizations"
    },
    {
     "expr": "sum by(instance) (irate(emqx_client_authenticate{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ instance }} Connection Authentication"
    },
    {
     "expr": "sum by(instance) (irate(emqx_client_authorize{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ instance }} Pub/Sub Authorization"
    },
    {
     "expr": "sum by(instance) (irate(emqx_client_auth_anonymous{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "{{ instance }} Anonymous Authentication"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Packets Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Connect"
    },
    {
     "expr": "sum(irate(emqx_packets_connack_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Connack Sent"
    },
    {
     "expr": "sum(irate(emqx_packets_connack_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Connack Error"
    },
    {
     "expr": "sum(irate(emqx_packets_connack_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Connack Auth Error"
    }
   ]
  },
  {
   "title": "Packets Disconnection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_disconnect_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Disconnect Sent"
    },
    {
     "expr": "sum(irate(emqx_packets_disconnect_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Disconnect Received"
    }
   ]
  },
  {
   "title": "Packets Publish",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_publish_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Sent"
    },
    {
     "expr": "sum(irate(emqx_packets_publish_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Received"
    },
    {
     "expr": "sum(irate(emqx_packets_publish_dropped{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Dropped"
    },
    {
     "expr": "sum(irate(emqx_packets_publish_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Error"
    },
    {
     "expr": "sum(irate(emqx_packets_publish_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Publish Auth Error"
    }
   ]
  },
  {
   "title": "Packets Subscribe/Unsubscribe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_subscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Subscribe Received"
    },
    {
     "expr": "sum(irate(emqx_packets_suback_sent{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Suback Sent"
    },
    {
     "expr": "sum(irate(emqx_packets_subscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Subscribe Error"
    },
    {
     "expr": "sum(irate(emqx_packets_subscribe_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Subscribe Auth Error"
    },
    {
     "expr": "sum(irate(emqx_packets_unsubscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Unsubscribe Received"
    },
    {
     "expr": "sum(irate(emqx_packets_unsubscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Packets Unsubscribe Error"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Cluster Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(emqx_messages_received{instance=~\".*\",cluster=\"$cluster\"}[20s]))",
     "legendFormat": "Messages Received"
    },
    {
     "expr": "sum(irate(emqx_messages_sent{instance=~\".*\",cluster=\"$cluster\"}[20s]))",
     "legendFormat": "Messages Sent"
    },
    {
     "expr": "sum(irate(emqx_messages_dropped{instance=~\".*\",cluster=\"$cluster\"}[20s]))",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Message Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "sum(emqx_vm_process_messages_in_queues{cluster=\"$cluster\", instance=~\".*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(instance) (emqx_vm_process_messages_in_queues{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_sessions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Sessions Total"
    }
   ]
  },
  {
   "title": "Cluster Traffic Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_bytes_received{instance=~\".*\",cluster=\"$cluster\"}[20s]) or irate(emqx_bytes_received{instance=~\".*\",cluster=\"$cluster\"}[20s]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(rate(emqx_bytes_sent{instance=~\".*\",cluster=\"$cluster\"}[20s]) or irate(emqx_bytes_sent{instance=~\".*\",cluster=\"$cluster\"}[20s]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Messages Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(emqx_messages_sent{cluster=\"$cluster\"}[20s]) or irate(emqx_messages_sent{cluster=\"$cluster\"}[20s]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_messages_received{cluster=\"$cluster\"}[20s]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages Dropped Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(emqx_messages_dropped{cluster=\"$cluster\"}[20s]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages QOS Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "expr": "sum(irate(emqx_messages_qos0_received{cluster=\"$cluster\", instance=~\".*\"}[20s]))",
     "legendFormat": "QOS0"
    },
    {
     "expr": "sum(irate(emqx_messages_qos1_received{cluster=\"$cluster\", instance=~\".*\"}[20s]))",
     "legendFormat": "QOS1"
    },
    {
     "expr": "sum(irate(emqx_messages_qos2_received{cluster=\"$cluster\", instance=~\".*\"}[20s]))",
     "legendFormat": "QOS2"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU Busy",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{job=\"node\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{job=\"node\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "timeseries",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (node_memory_MemAvailable_bytes{job=\"node\"} * 100)) / sum by(instance) (node_memory_MemTotal_bytes{job=\"node\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (process_max_fds{job=\"node\"})",
     "legendFormat": "{{ instance }} Maximum open file descriptors"
    },
    {
     "expr": "sum by(instance) (process_open_fds{job=\"node\"})",
     "legendFormat": "{{ instance }} Open file descriptors"
    }
   ]
  },
  {
   "title": "Mnesia (built-in database) Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (erlang_mnesia_memory_usage_bytes{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Erlang VM Run Queue",
   "type": "timeseries",
   "description": "The value of run_queue_length can be used to evaluate the current Erlang scheduler load. If the value of run_queue_length is high, it means that there are many processes waiting to be executed in the run queue, and the scheduler may need more processor cores or a better scheduling strategy to better handle these processes",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by(instance) (erlang_vm_statistics_run_queues_length_total{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }} Run Queue Length"
    }
   ]
  },
  {
   "title": "Erlang VM Process",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "max by(instance) (erlang_vm_process_limit{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }} Max Process limit"
    },
    {
     "expr": "sum by(instance) (erlang_vm_process_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }} Process Count"
    }
   ]
  },
  {
   "title": "Erlang VM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (emqx_vm_used_memory{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}