{
 "title": "Authentication",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   { "name": "node", "query": { "query": "label_values(node)" } },
   {
    "name": "resource",
    "query": {
     "query": "label_values(emqx_authentication_resource_status,resource)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Authenticate Count",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(node, resource) (emqx_authentication_exec_max_rate{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(node, resource) (emqx_authentication_total{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(node, resource) (emqx_authentication_allow_count{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(node, resource) (increase(emqx_authentication_deny_count{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"}[15m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Authenticate Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(node, resource) (emqx_authentication_exec_rate{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "{{node}} {{resource}}"
    }
   ]
  },
  {
   "title": "Authenticate Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "sum by(node, resource) (emqx_authentication_exec_last5m_rate{cluster=\"$cluster\", node=~\"$node\", resource=~\"$resource\"})",
     "legendFormat": "{{node}} {{resource}}"
    }
   ]
  }
 ]
}