{
 "title": "EMQX",
 "description": "Default EMQX Grafana Monitoring Dashboard Template",
 "tags": [
  "EMQX",
  "MQTT"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emqx_cluster_status{cluster=\"$cluster\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(emqx_license_max_client_limit{cluster=\"$cluster\"})",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "Cluster Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "emqx_messages_input_period_second{cluster=\"$cluster\"}",
     "legendFormat": "Msg Input Period Second"
    },
    {
     "expr": "emqx_messages_output_period_second{cluster=\"$cluster\"}",
     "legendFormat": "Msg Output Period Second"
    }
   ]
  },
  {
   "title": "Nodes Running",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "max(emqx_cluster_nodes_running{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max(emqx_cluster_nodes_stopped{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Stopped"
    }
   ]
  },
  {
   "title": "Exporter Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(emqx_scrape_collector_duration_seconds{cluster=\"$cluster\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "License",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(emqx_license_remaining_days{cluster=\"$cluster\"})",
     "legendFormat": "Days Remaining"
    },
    {
     "expr": "sum(emqx_license_expiration_time{cluster=\"$cluster\"})",
     "legendFormat": "Expiry At"
    },
    {
     "expr": "sum(emqx_license_max_client_limit{cluster=\"$cluster\"})",
     "legendFormat": "Max Conns"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_live_connections_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(instance) (emqx_connections_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(emqx_suboptions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(emqx_sessions_count{instance=~\".*\", cluster=\"$cluster\"})",
     "legendFormat": "Count"
    },
    {
     "expr": "sum(emqx_license_max_client_limit{cluster=\"$cluster\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Rule Engine Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  },
  {
   "title": "Connect Auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval])) - sum(irate(emqx_packets_connack_error {instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Auth Success"
    },
    {
     "expr": "sum(irate(emqx_packets_connack_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Auth Failure"
    }
   ]
  },
  {
   "title": "ACL Auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(emqx_packets_publish_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Publish ACL Failure"
    },
    {
     "expr": "sum(irate(emqx_packets_subscribe_auth_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Sub ACL Failure "
    }
   ]
  },
  {
   "title": "Data Bridge Queuing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(type, name) (emqx_rule_bridge_queuing{cluster=\"$cluster\"})",
     "legendFormat": "{{type}}-{{name}}"
    }
   ]
  },
  {
   "title": "Rule Engine Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_exec_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{ rule }}"
    }
   ]
  },
  {
   "title": "Rule Engine Exec Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Rule Engine Exec Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Rule Engine Action Success",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_action_success{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Rule Engine Action Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "sum by(rule) (irate(emqx_rule_action_failed{cluster=\"$cluster\", node=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  { "title": "Event", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Client Connection Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(irate(emqx_client_connected{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(irate(emqx_client_disconnected{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Disconnections"
    }
   ]
  },
  {
   "title": "Client Sub Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "sum(irate(emqx_client_subscribe{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "Subscribes"
    },
    {
     "expr": "sum(irate(emqx_client_unsubscribe{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "Unsubscribes"
    }
   ]
  },
  {
   "title": "Client Connect Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(irate(emqx_client_authenticate{cluster=\"$cluster\",instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "Connect Auth"
    },
    {
     "expr": "sum(irate(emqx_client_auth_anonymous{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "Anonymous Auth"
    }
   ]
  },
  {
   "title": "Client ACL Auth Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "sum(irate(emqx_client_authorize{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "ACL Auth"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_connect{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Connect"
      },
      {
       "expr": "sum(irate(emqx_packets_connack_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Connack Sent"
      },
      {
       "expr": "sum(irate(emqx_packets_connack_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Connack Error"
      }
     ]
    },
    {
     "title": "Packets Disconnections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_disconnect_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Disconnect Sent"
      },
      {
       "expr": "sum(irate(emqx_packets_disconnect_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Disconnect Received"
      }
     ]
    },
    {
     "title": "Packets Publish",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_publish_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Sent"
      },
      {
       "expr": "sum(irate(emqx_packets_publish_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Received"
      },
      {
       "expr": "sum(irate(emqx_packets_publish_dropped{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Dropped"
      },
      {
       "expr": "sum(irate(emqx_packets_publish_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Publish Error"
      }
     ]
    },
    {
     "title": "Packets Subscribe/Unsubscribe",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
     "targets": [
      {
       "expr": "sum(irate(emqx_packets_subscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Subscribe Received"
      },
      {
       "expr": "sum(irate(emqx_packets_suback_sent{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Suback Sent"
      },
      {
       "expr": "sum(irate(emqx_packets_subscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Subscribe Error"
      },
      {
       "expr": "sum(irate(emqx_packets_unsubscribe_received{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Unsubscribe Received"
      },
      {
       "expr": "sum(irate(emqx_packets_unsubscribe_error{instance=~\".*\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Packets Unsubscribe Error"
      }
     ]
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Messages Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(emqx_messages_received{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Messages Received"
    },
    {
     "expr": "sum(irate(emqx_messages_sent{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Messages Sent"
    },
    {
     "expr": "sum(irate(emqx_messages_dropped{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Messages QOS Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum(irate(emqx_messages_qos0_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "QOS0"
    },
    {
     "expr": "sum(irate(emqx_messages_qos1_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "QOS1"
    },
    {
     "expr": "sum(irate(emqx_messages_qos2_received{cluster=\"$cluster\", instance=~\".*\"}[$__rate_interval]))",
     "legendFormat": "QOS2"
    }
   ]
  },
  {
   "title": "Cluster Traffic Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(emqx_bytes_received{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(irate(emqx_bytes_sent{instance=~\".*\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Rule Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Data Bridge Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(type, name) (emqx_rule_bridge_status{cluster=\"$cluster\"})",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by(type, name) (emqx_rule_bridge_queuing{cluster=\"$cluster\"})",
     "legendFormat": "Queuing"
    }
   ]
  },
  {
   "title": "Rule Engine Execute Count",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 48 },
   "targets": [
    {
     "expr": "sum by(rule) (emqx_rule_topic_hit_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Topic Hit Cout"
    },
    {
     "expr": "max by(rule) (emqx_rule_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Max Rate"
    },
    {
     "expr": "sum by(rule) (emqx_rule_exec_pass_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Exec Pass"
    },
    {
     "expr": "sum by(rule) (irate(emqx_rule_exec_failure_count{cluster=\"$cluster\", node=~\".*\"}[15m]))",
     "legendFormat": "Exec Failure"
    },
    {
     "expr": "sum by(rule) (emqx_rule_exec_no_result_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Exec No Result"
    },
    {
     "expr": "sum by(rule) (emqx_rule_action_total{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Action Total"
    },
    {
     "expr": "sum by(rule) (emqx_rule_action_success{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Action Success"
    },
    {
     "expr": "sum by(rule) (increase(emqx_rule_action_failed{cluster=\"$cluster\", node=~\".*\"}[15m]))",
     "legendFormat": "Action Failed"
    }
   ]
  },
  { "title": "Connect Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Authenticate Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by(resource) (emqx_authentication_resource_status{cluster=\"$cluster\"})",
     "legendFormat": "Status"
    },
    {
     "expr": "max by(resource) (emqx_authentication_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(resource) (emqx_authentication_total{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(resource) (emqx_authentication_allow_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(resource) (irate(emqx_authentication_deny_count{cluster=\"$cluster\", node=~\".*\"}[15m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Authenticate Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 54 },
   "targets": [
    {
     "expr": "sum by(resource) (emqx_authentication_exec_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Authenticate Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 54 },
   "targets": [
    {
     "expr": "sum by(resource) (emqx_authentication_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "ACL Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Authorize Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by(resource) (emqx_authorization_resource_status{cluster=\"$cluster\"})",
     "legendFormat": "Status"
    },
    {
     "expr": "max by(resource) (emqx_authorization_exec_max_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Max Rate"
    },
    {
     "expr": "sum by(resource) (emqx_authorization_total{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(resource) (emqx_authorization_allow_count{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "Allow"
    },
    {
     "expr": "sum by(resource) (irate(emqx_authorization_deny_count{cluster=\"$cluster\", node=~\".*\"}[15m]))",
     "legendFormat": "Deny"
    }
   ]
  },
  {
   "title": "Authorize Current Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 61 },
   "targets": [
    {
     "expr": "sum by(resource) (emqx_authorization_exec_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Authorize Last 5m Exec Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 61 },
   "targets": [
    {
     "expr": "sum by(resource) (emqx_authorization_exec_last5m_rate{cluster=\"$cluster\", node=~\".*\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Last 1m CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load1\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Last 5m CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load5\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Last 15m CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "expr": "sum by(node) (emqx_cluster_cpu_load{cluster=\"$cluster\", load=\"load15\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}