metrics:
  ## EMQX API
  target: 127.0.0.1:18083
  ## EMQX API key
  api_key: "76668f8a2003d597"
  ## EMQX API secret
  api_secret: "CRCDB6lxxzN58e5HoD82llBC0Erg1TVZIAUsdTjPU7N"
probes:
  - target: broker.emqx.io:1883 ## MQTT broker address
    scheme: ## tcp, default is tcp
    client_id:
    username:
    password:
    topic:
    qos:
