probes:
  - target: 127.0.0.1:1883
  - target: 127.0.0.1:8883
    scheme: ssl
    ssl_config:
      insecure_skip_verify: true
      ca_file: config/example/certs/cacert.pem
      cert_file: config/example/certs/client-cert.pem
      key_file: config/example/certs/client-key.pem
