version: '3.8'
services:
  emqx:
    image: emqx/emqx-enterprise:5.3
    container_name: emqx-demo
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
    environment:
      EMQX_DASHBOARD__BOOTSTRAP_USERS_FILE: '"/opt/emqx/data/api_secret"'
      EMQX_API_KEY__BOOTSTRAP_FILE: '"/opt/emqx/data/api_secret"'
    volumes:
      - ./api_secret:/opt/emqx/data/api_secret
    healthcheck:
      test: ["CMD", "emqx", "ctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  emqx-exporter:
    depends_on:
      - emqx
    image: emqx-exporter
    container_name: exporter-demo
    # ports:
      # - 8085:8085
    volumes:
      - ./emqx-exporter.config.yaml:/etc/emqx-exporter/config.yaml

  prometheus:
    image: prom/prometheus
    container_name: prometheus-demo
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-emqx5.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana-demo
    ports:
      - 3000:3000
    volumes:
      - ../../grafana-dashboard/template/emqx-enterprise-5:/grafana-dashboard-definitions
      - ../provisioning/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ../provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
