global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'emqx'
    metrics_path: /api/v5/prometheus/stats
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      # a list of addresses of all EMQX nodes
      - targets: [emqx-demo:18083]
        labels:
          # label the cluster name of where the metrics data from
          cluster: test
          # fix value, don't modify
          from: emqx
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "instance"
        regex: (.*):.*
        replacement: $1
  - job_name: 'exporter'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: [exporter-demo:8085]
        labels:
          # label the cluster name of where the metrics data from
          cluster: test
          # fix value, don't modify
          from: exporter
  - job_name: 'mqtt-probe'
    metrics_path: '/probe'
    params:
      target:
        - "emqx-demo:1883"
    scrape_interval: 5s
    static_configs:
      - targets: [exporter-demo:8085]
        labels:
          # label the cluster name of where the metrics data from
          cluster: test
          # fix value, don't modify
          from: probe
  - job_name: 'mqtts-probe'
    metrics_path: '/probe'
    params:
      target:
        - "emqx-demo:8883"
    scrape_interval: 5s
    static_configs:
      - targets: [exporter-demo:8085]
        labels:
          # label the cluster name of where the metrics data from
          cluster: test
          # fix value, don't modify
          from: probe
  - job_name: 'ws-probe'
    metrics_path: '/probe'
    params:
      target:
        - "emqx-demo:8083/mqtt"
    scrape_interval: 5s
    static_configs:
      - targets: [exporter-demo:8085]
        labels:
          # label the cluster name of where the metrics data from
          cluster: test
          # fix value, don't modify
          from: probe
  - job_name: 'wss-probe'
    metrics_path: '/probe'
    params:
      target:
        - "emqx-demo:8084/mqtt"
    scrape_interval: 5s
    static_configs:
      - targets: [exporter-demo:8085]
        labels:
          # label the cluster name of where the metrics data from
          cluster: test
          # fix value, don't modify
          from: probe
