name: golangci-lint
on:
  push:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".github/workflows/golangci-lint.yml"
      - ".golangci.yml"
  pull_request:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".github/workflows/golangci-lint.yml"
      - ".golangci.yml"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go install github.com/google/go-licenses@latest
      - run: $(go env GOPATH)/bin/go-licenses check . --disallowed_types forbidden,restricted,unknown
      - name: Lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.51.2
    
  license-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go install github.com/google/go-licenses@latest
      - run: $(go env GOPATH)/bin/go-licenses check . --disallowed_types forbidden,restricted,unknown
