apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/prometheus-operator/kube-prometheus.git?ref=main
- resources/emqx-exporter.yaml
- resources/emqx.yaml

patches:
- path: patches/grafana-dashboards-configmap.yaml
- path: patches/grafana.yaml

configMapGenerator:
- name: emqx-grafana-overview
  namespace: monitoring
  files:
  - grafana-dashboard/overview.json
- name: emqx-grafana-authentication
  namespace: monitoring
  files:
  - grafana-dashboard/authentication.json
- name: emqx-grafana-authorization
  namespace: monitoring
  files:
  - grafana-dashboard/authorization.json
- name: emqx-grafana-client-events
  namespace: monitoring
  files:
  - grafana-dashboard/client-events.json
- name: emqx-grafana-messages
  namespace: monitoring
  files:
  - grafana-dashboard/messages.json
- name: emqx-grafana-rule-engine
  namespace: monitoring
  files:
  - grafana-dashboard/rule-engine.json
